version: "3.8"
services:
  db:
    image: postgres:15
    container_name: crawler_postgres
    restart: always
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crawler:
    build: .
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: